-- 코드를 입력하세요
SELECT TITLE, b.BOARD_ID, REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r on b.board_ID = r.board_ID
WHERE  DATE_FORMAT('2022-10-01', '%Y-%m-%d')<= b.CREATED_DATE AND b.CREATED_DATE <= DATE_FORMAT('2022-10-30','%Y-%m-%d')
ORDER BY CREATED_DATE ASC, TITLE ASC;